### ISSUE TITLE
DataStore body edge case

### ISSUE THREAD

**Issue by guidojw** [Daw588/roblox.js#1]
Hi, nice package!

I have stumbled upon an error: when Roblox returns "inf" for way too large numbers in the return body like:
![image](https://user-images.githubusercontent.com/35309288/166317868-5e696f9d-f2db-4411-bda8-09dfbb18a531.png)

`node-fetch`'s body.json() will error on this:

![image](https://user-images.githubusercontent.com/35309288/166318016-fb0242c5-4261-4a9b-b58b-c96c2583d334.png)

**Comment by Daw588** [comment]
So from what I am understanding, is that an ugly JSON error pops up when you call the `GetAsync()` function on a key that contains a large number value? If so, what exactly is the issue? Do you want more meaningful error message or a fix (if possible) to correct the large number issue? Nonetheless, thank you for reporting this issue.

**Comment by guidojw** [comment]
The issue is that Roblox returns inf in the body which is not valid JSON, it would be great if this somehow can be replaced with another value before calling response.json().

I used RbxDataStoreService by nikitapetko before the move to this package and that package somehow turns inf into undefined. I don't know if this is done manually or just a result of it not being valid JSON. But at least it doesn't throw :)

**Comment by Daw588** [comment]
I get what you meant now, it's an infinite value that Roblox formats as `inf`. I will attempt to fix it when I can by replacing the `inf` with the JavaScript's `Infinity`.

**Comment by Daw588** [comment]
I have fixed this in `0.0.6`, as I implemented pre-processing, which will replace all instances of `inf` with `Infinity`.
