### ISSUE TITLE
More meaningful errors

### ISSUE THREAD

**Issue by guidojw** [Daw588/roblox.js#2]
Currently errors are just strings:

https://github.com/Daw588/roblox.js/blob/5e38a40dbb8ce71dbbb0ac95d3c4e8d57d56dbb8/src/modules/datastore.ts#L183

It would be great if stuff like the HTTP status and statusText could easily be retrieved from this error (without parsing the string).

**Comment by Daw588** [comment]
Would this format be fine?
```js
{
    status: 404,
    statusText: "Not Found"
}
```

**Comment by Daw588** [comment]
Do you want me to return a `Promise.reject()` with the Https error so that you can get it in a try catch function?

**Comment by guidojw** [comment]
> Do you want me to return a `Promise.reject()` with the Https error so that you can get it in a try catch function? Is that what you meant?

Yes, I would like to be able to catch the errors and check the status code of them. (For example 404 to see if a key doesn't exist yet)

**Comment by Daw588** [comment]
Thanks for your feedback. I added this in the `0.0.6` version, which you can upgrade to right now.
