### ISSUE TITLE
ESM import error

### ISSUE THREAD

**Issue by guidojw** [Daw588/roblox.js#3]
When I import like:
```ts
import { Universe, DataStore } from '@daw588/roblox.js'
```
I get the following error:
![image](https://user-images.githubusercontent.com/35309288/166319087-f92f63e9-0c9a-4b7f-b86c-9f75ee557a4e.png)

Importing like:
```ts
import { Universe, DataStore } from '@daw588/roblox.js/dist/index.js'
```
works however.

What could be going wrong here? I am not very experienced with the TypeScript NodeNext `module` and `moduleResolution` options yet. [Here](https://github.com/guidojw/credits-gibber/tree/feat/open-cloud)'s my relevant code if you're interested.

**Comment by Daw588** [comment]
I am not sure on what is going wrong here, I will let you know when this gets fixed, but for now I will leave it as it is until I find a proper solution.

**Comment by Daw588** [comment]
Hey guidojw, I have released a patch for this issue. Let me know if it's fixed for you so that I can close this issue.
