### ISSUE TITLE
datastore SetAsync error?

### ISSUE THREAD

**Issue by NotVEVO** [Daw588/roblox.js#4]
I receive these errors when trying to use SetAsync on a datastore. (The values used are replaced with placeholder)

`const universe = new Universe(id, key);`
`const GuildedTagStore = new DataStore(universe, name);`

`await GuildedTagStore.SetAsync(DataStoreName, data);`

![image](https://user-images.githubusercontent.com/18171728/181502423-2146856c-0398-4511-b73a-6936a1ca7d68.png)

**Comment by Daw588** [comment]
What was the value you tried to set using the `SetAsync` function?

**Comment by NotVEVO** [comment]
First I was using a dictionary, then I tried using a normal number value. Both of them returned an error

**Comment by Daw588** [comment]
Can you give me an example of what you tried, so that I try to reproduce the issue myself?

**Comment by NotVEVO** [comment]
Turns out the error was on my end, my apologies.
