### ISSUE TITLE
Base JavaScript support

### ISSUE THREAD

**Issue by Rythian2277** [Daw588/roblox.js#5]
At the moment, attempting to use this module with a normal JS project results in the error that it must be listed as a `"type": "module"` which breaks my whole project which is written in standard JS, not TS. Is it possible to have this module work with normal JS or would it require a full rewrite of my program to support it?

**Comment by Certurix** [comment]
Same for me, currently strugling to add roblox.js to my current JS project as @Rythian2277 mentionned.

**Comment by Daw588** [comment]
This library is written in TypeScript, however it is transpiled to JavaScript, so what you're using is a JavaScript build, though it is ES6, which uses `import` and `export` which are not supported in common JavaScript. I'm not sure what you could besides rewriting your project to ES6 and up. Perhaps try using dynamic import like this:
```js
import("@daw588/roblox.js").then(v => console.log(v));
```
