### ISSUE TITLE
Datastore.GetAsync explicity assumes that every key's value is in JSON format

### ISSUE THREAD

**Issue by choke-dev** [Daw588/roblox.js#6]

**Comment by Daw588** [comment]
Can you provide an example where the key is not in JSON format?

**Comment by Reapimus** [comment]
> Can you provide an example where the key is not in JSON format?

Datastores don't demand developers store explicitly only JSON inside of them, datastores allow developers to just directly store a number or string as well.

**Comment by Daw588** [comment]
I have tested both `number`, `string`, and tables, and they are returned just fine from `GetAsync`, so I'm unsure of what the issue is here. Single `string`, and `number` are valid JSON.
